version: '3'

services:
  ctfd:
    container_name: ctfd
    image: ctfd/ctfd
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=Host:$BASE_DOMAIN'
      - 'traefik.docker.network=$TRAEFIK_NETWORK'
    networks:
      - traefik

  crummy:
    container_name: crummy
    build: ./web/crummy
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=Host:crummy.$BASE_DOMAIN'
      - 'traefik.docker.network=$TRAEFIK_NETWORK'
    networks:
      - traefik

  overflow:
    container_name: overflow
    build: ./pwn/0v3rfl0w
    restart: unless-stopped
    ports:
      - '6001:6001'

  clock:
    container_name: clock
    build: ./misc/clock
    restart: unless-stopped
    ports:
      - '6003:6003'

networks:
  traefik:
    external:
      name: $TRAEFIK_NETWORK
